[tool.poetry]
name = "cyber-physical-tools"
version = "0.1.0"
description = "Tools for deep learning on cyber-physical systems."
authors = ["Damian Owerko <Damowerko@users.noreply.github.com>"]
readme = "README.md"
packages = [{include = "cyber_physical_tools"}]

[tool.poetry.dependencies]
python = "^3.11,<3.12"
torch = "^2.0.1"
pytorch-lightning = "^2.0.5"
numpy = "^1.25.1"
torch-geometric = "^2.3.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
