[tool.poetry]
name = "torchcps"
version = "0.1.0"
description = "Tools for deep learning on cyber-physical systems."
authors = ["Damian Owerko <Damowerko@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11,<3.12"
pytorch-lightning = "^2.0.5"
numpy = "^1.25.1"
torch-geometric = "^2.3.1"
torch = "^2.0.1"
pykeops = "^2.1.2"
matplotlib = "^3.7.2"
seaborn = "^0.12.2"
tqdm = "^4.65.0"
pandas = "^2.0.3"
scipy = "^1.11.1"
scikit-learn = "^1.3.0"
torchdata = "^0.6.1"


[tool.poetry.group.dev.dependencies]
pytest = "^7.4.0"
jupyter = "^1.0.0"
black = "^23.7.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
