[tool.poetry]
name = "torchcps"
version = "0.1.0"
description = "Tools for deep learning on cyber-physical systems."
authors = ["Damian Owerko <Damowerko@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11,<3.12"
pytorch-lightning = ">=2.0.0"
numpy = "^1.25.1"
torch = {version = "=2.0.0"}
torch-geometric = {version = "^2.3.1"}
pykeops = "^2.1.2"
matplotlib = ">=3.0.0"
seaborn = ">=0.12.0"
tqdm = "4.*"
pandas = "2.*"
scipy = "1.*"
scikit-learn = "^1.3.0"
torch-sparse = "^0.6.17+pt20cu118"
torch-cluster = "^1.6.3+pt20cu118"


[tool.poetry.group.dev.dependencies]
pytest = "^7.4.0"
jupyter = "^1.0.0"
black = "^23.7.0"

[[tool.poetry.source]]
name = "PyPI"
priority = "supplemental"

[[tool.poetry.source]]
name = "pyg"
url = "https://data.pyg.org/whl/torch-2.0.0+cu118.html"
priority = "primary"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
